#Là một cấu trúc dữ liệu dùng để lưu giữ các đối tượng Theo quy tắc vào sau ra trước
install.packages('dequer')
library(dequer)
s <- stack()
for (i in 1:5) push(s, i)
str(s)
pop(s)
str(s)
pop(s)
str(s)
pop(s)
str(s)
